<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/udochi/image/upload/v1554479476/IMG_1671.jpg" alt="Udochi Kaduru">
                        <h6>Udochi Kaduru</h6>
                        <p>Product Designer</p>
                        <ul class="list">
                           <li><a href="#" target="_blank"<i class="fab fa-twitter fa-2x"></i></a>https://twitter.com/UD0CHI</li>
                           <li><a href="#" target="_blank"<i class="fab fa-github fa-2x"></i></a>https://github.com/udochii</li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a>https://medium.com/@udochii</li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi, i'm Udochi. I'm a Product Designer and I enjoy meeting new people and finding ways to help them have an uplifting experience.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>UX | Creative Writing | Drawing</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
